database:
  location: "./_/_db"

server:
  port: 9898
  maxWordsAllowed: 320
  ginMode: debug
  sessionSecret: dev
  title: lark

user:
  name: test
  password: test

az:
  connStr:
  blobContainer: dev
  blob: db.json
  backupInterval: 1