database:
  location: "./_/_db"

server:
  port: 9898
  mode: diary
  ginMode: debug
  sessionSecret: dev

user:
  name: test
  password: test

az:
  connStr:
  blobContainer: dev
  blob: db.json
  backupInterval: 1